---
version: '2'
services:

  traceability-api:
    build:
      context: .
    container_name: traceability-api
    restart: unless-stopped
    entrypoint: ["python", "main.py"]
    environment:
      TRACEABILITY_DOMAIN_NAME: ${TRACEABILITY_DOMAIN_NAME}
      TRACEABILITY_ADMIN_API_KEY: ${TRACEABILITY_ADMIN_API_KEY}
      TRACTION_API_ENDPOINT: ${TRACTION_API_ENDPOINT}
      TRACTION_TENANT_ID: ${TRACTION_TENANT_ID}
      TRACTION_API_KEY: ${TRACTION_API_KEY}

      JWT_SECRET: ${JWT_SECRET}

      VERIFIER_ENDPOINT: http://verifier-agent:8020
      POSTGRES_URI: postgres://${POSTGRES_USER}:${POSTGRES_PASS}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      ASKAR_KEY: ${ASKAR_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.traceability-api.rule=Host(`${TRACEABILITY_DOMAIN_NAME}`)
      - traefik.http.routers.traceability-api.entrypoints=websecure
      - traefik.http.routers.traceability-api.tls.certresolver=myresolver
      - traefik.http.services.traceability-api.loadbalancer.server.port=8000

  # verifier-agent:
  #   # image: ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.10.4
  #   build:
  #     context: ../aries-cloudagent-python
  #     dockerfile: docker/Dockerfile
  #   container_name: verifier-agent
  #   restart: unless-stopped
  #   # ports:
  #   #   - 8020:8020
  #   entrypoint: ["aca-py", "start"]
  #   command: [
  #     '--no-ledger',
  #     '--admin-insecure-mode',
  #     '--endpoint', 'http://localhost',
  #     '--admin', '0.0.0.0', '8020',
  #     '--outbound-transport', 'http',
  #     '--inbound-transport', 'http', '0.0.0.0', '8021'
  #   ]

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.myresolver.acme.tlschallenge=true
      - --certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}
      - --certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json
    ports:
      - 443:443
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  letsencrypt:
  postgres_data:
